-- AlterTable
ALTER TABLE `activities` MODIFY `type` ENUM('GAME_CREATED', 'GAME_UPDATED', 'GAME_DELETED', 'GAME_REGISTERED', 'USER_UPDATED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_BANNED', 'USER_UNBANNED') NOT NULL;
