import Link from "next/link";

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-16">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Welcome to Scavenger Hunt Platform
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Embark on epic adventures, solve AI-powered clues, and collect pebbles 
            in location-based scavenger hunts around the world.
          </p>
          <div className="flex gap-4 justify-center">
            <Link 
              href="/auth/register"
              className="bg-gradient-to-r from-emerald-600 to-teal-700 text-white px-8 py-3 rounded-lg font-semibold hover:from-emerald-700 hover:to-teal-800 transition-all duration-300 transform hover:scale-105 shadow-lg"
            >
              Get Started
            </Link>
            <Link 
              href="/games"
              className="bg-gradient-to-r from-amber-500 to-orange-600 text-white px-8 py-3 rounded-lg font-semibold hover:from-amber-600 hover:to-orange-700 transition-all duration-300 transform hover:scale-105 shadow-lg border-2 border-amber-400"
            >
              View Games
            </Link>
          </div>
        </div>

        {/* Features */}
        <div id="features" className="grid md:grid-cols-3 gap-8 mb-16">
          <div id="feature-1" className="group relative overflow-hidden bg-blue-400 p-8 rounded-2xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:scale-105 border-2 border-blue-500">
            <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/40 rounded-full -translate-y-16 translate-x-16"></div>
            <div className="relative z-10">
              <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform border-2 border-blue-700">
                <span className="text-3xl">🧩</span>
              </div>
              <h3 className="text-2xl font-bold text-blue-900 mb-4">AI-Powered Clues</h3>
              <p className="text-blue-800 leading-relaxed">
                Experience intelligent clues generated by AI based on your location and the game theme.
              </p>
            </div>
          </div>
          
          <div className="group relative overflow-hidden bg-emerald-400 p-8 rounded-2xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:scale-105 border-2 border-emerald-500">
            <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/40 rounded-full -translate-y-16 translate-x-16"></div>
            <div className="relative z-10">
              <div className="w-16 h-16 bg-emerald-600 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform border-2 border-emerald-700">
                <span className="text-3xl">📍</span>
              </div>
              <h3 className="text-2xl font-bold text-emerald-900 mb-4">Location-Based</h3>
              <p className="text-emerald-800 leading-relaxed">
                Hunt in your real location with GPS-powered challenges that adapt to where you are.
              </p>
            </div>
          </div>
          
          <div className="group relative overflow-hidden bg-pink-400 p-8 rounded-2xl shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:scale-105 border-2 border-pink-500">
            <div className="absolute top-0 right-0 w-32 h-32 bg-pink-500/40 rounded-full -translate-y-16 translate-x-16"></div>
            <div className="relative z-10">
              <div className="w-16 h-16 bg-pink-600 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform border-2 border-pink-700">
                <span className="text-3xl">💎</span>
              </div>
              <h3 className="text-2xl font-bold text-pink-900 mb-4">Collect Pebbles</h3>
              <p className="text-pink-800 leading-relaxed">
                Earn pebbles for solving clues and use them to access new stages and levels.
              </p>
            </div>
          </div>
        </div>

        {/* Game Progression */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-500 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                1
              </div>
              <h4 className="font-semibold mb-2">Register & Join</h4>
              <p className="text-sm text-gray-600">Sign up and register for available games</p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-green-500 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                2
              </div>
              <h4 className="font-semibold mb-2">Solve Clues</h4>
              <p className="text-sm text-gray-600">Complete 4-5 clues per hunt using text or photos</p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-purple-500 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                3
              </div>
              <h4 className="font-semibold mb-2">Progress Through Stages</h4>
              <p className="text-sm text-gray-600">Complete 4 stages per level, earn badges</p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-yellow-500 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
                4
              </div>
              <h4 className="font-semibold mb-2">Master All Levels</h4>
              <p className="text-sm text-gray-600">Conquer all 12 levels to become a master</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
