name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typecheck-and-lint:
    name: TypeScript Check & Lint
    runs-on: ubuntu-latest
    
    env:
      # Minimal env vars needed for type checking and building
      DATABASE_URL: "mysql://placeholder:placeholder@localhost:3306/placeholder_db"
      JWT_SECRET: "placeholder-jwt-secret-for-ci-only"
      JWT_REFRESH_SECRET: "placeholder-refresh-secret-for-ci-only"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Generate Prisma Client (no DB connection needed)
      run: yarn db:generate
      
    - name: TypeScript Check
      run: yarn type-check
      
    - name: ESLint Check
      run: yarn lint
      
    - name: Build Check (static build, no DB needed)
      run: yarn build
      
  security-check:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run security audit
      run: yarn audit --level moderate
      continue-on-error: true
